### ISSUE TITLE
Unable to start JupyterHub servers

### ISSUE THREAD

**Issue by ThomasWarford** [jean-zay-users/jean-zay-doc#105]
Hi,
When I try to start a Jupyter server, I get this error:
```
Error: No spawner type detected. Please choose one of the spawner types provided in the dropdown in the Server Options form
```

There doesn't seem to be a dropdown for spawner types.

Has anyone else had/resolved this issues?

Thanks!

**Comment by RemiLacroix-IDRIS** [comment]
Hi. Have you tried the erasing your cache/cookies or using the private mode of your browser?

**Comment by ThomasWarford** [comment]
Yes, unfortunately it doesn't work in a private window.

**Comment by RemiLacroix-IDRIS** [comment]
Could you try removing `~/.jupyter*` folders just in case?

**Comment by ThomasWarford** [comment]
Thanks for the reply. There aren't any files matching `~/.jupyter*` at the moment. No, this is my first time trying to use JupyterHub.

I'll try with Firefox quickly and let you know if it works :)

**Comment by ThomasWarford** [comment]
It seems to be working with Firefox, thank you for the help

**Comment by RemiLacroix-IDRIS** [comment]
You are welcome.
