### ISSUE TITLE
Document how to monitor GPU usage within a job

### ISSUE THREAD

**Issue by lesteve** [jean-zay-users/jean-zay-doc#36]
Since recently you can `ssh` to a node where one of your job is running and run any monitoring command you want there e.g. `nvidia-smi`.

See [this](http://www.idris.fr/eng/jean-zay/jean-zay-connexion_ssh_noeud_calcul-eng.html) for more details.

**Comment by RemiLacroix-IDRIS** [comment]
The English version is now available: http://www.idris.fr/eng/jean-zay/jean-zay-connexion_ssh_noeud_calcul-eng.html.

**Comment by lesteve** [comment]
Closed by #45.
