### ISSUE TITLE
Longer term evolution with jupyter-book

### ISSUE THREAD

**Issue by lesteve** [jean-zay-users/jean-zay-doc#5]
I think jupyter book looks good. It seems a quick way of getting a reasonably good-looking documentation from `.md` files and potentially in the future Jupyter notebooks for some tutorials:

https://github.com/jupyter/jupyter-book
https://jupyterbook.org

The Turing way uses it:
https://the-turing-way.netlify.com/introduction/introduction

**Comment by mdiazmel** [comment]
Hi @lesteve ,
I'm working in a mkdocs version hosted by readthedocs. I'll prepare a PR to have an initial view.

**Comment by lesteve** [comment]
Closing thanks to #47.
