### ISSUE TITLE
Renew hours after one year

### ISSUE THREAD

**Issue by lesteve** [jean-zay-users/jean-zay-doc#52]
Since allocated hours are for one year, after one year you may want to renew them.

https://www.edari.fr/utilisateur
![image](https://user-images.githubusercontent.com/1680079/101598915-2b3d2700-39f9-11eb-9b81-3c8973996aa0.png)

Select project in "Renouvellement d'un projet antérieur" section:
![snap](https://user-images.githubusercontent.com/1680079/101599715-84598a80-39fa-11eb-9a29-1531a452fa5c.png)

~~and now I am stuck (i.e. selecting my project does not open a page or lead to some new content in the current page), maybe this is because "Notez que vous ne pouvez renouveler un dossier que s'il a obtenu des heures." means I need to ask for some hours before being able to renew the project :confused:  ...~~

~~**Edit**: problem is fixed I am adding more screenshots as I go along.~~
![image](https://user-images.githubusercontent.com/1680079/101633158-2c854880-3a27-11eb-8f80-ae264d5b9e24.png)

After many pages where you mostly say yes, yes, yes and tick boxes:
![registered](https://user-images.githubusercontent.com/1680079/103563694-7bef5500-4ebd-11eb-8be0-fd0ffc9cae98.png)

Now you need to add a report of what you did last year, click on "Déposer le rapport d'activité du dossier précédent" where you need to upload a PDF. Mention the papers you have written (or you are preparing) for which you have used Jean Zay resources (reminder you need to put GENCI in the acknowledgements as mentioned in http://www.idris.fr/eng/info/gestion/remerciements-eng.html). The basic idea behind the activity report is that you asked for some hours and you need to show that you have used them well. From some user feed-back, writing half a page should be enough.
 
![image](https://user-images.githubusercontent.com/1680079/101634879-90a90c00-3a29-11eb-8f1d-5f0644e85ef8.png)

Don't forget to click on the "Valider le dossier" button to actually validate your renewal!

You should see something like this:

![validate](https://user-images.githubusercontent.com/1680079/103563584-4ba7b680-4ebd-11eb-9dcf-91af94975420.png)

**TODO: mention how long it takes to get an answer** for now estimate is roughly 1 week.

**Comment by RemiLacroix-IDRIS** [comment]
Hmm that's weird, I think you are doing the right thing based on our documentation (currently being translated to English): http://www.idris.fr/info/gestion/demande-heures/documentation-ad/renouvellement-dossier-ad.html.

**Comment by lesteve** [comment]
So I cam select the line (note the blue dot on the left-hand side) but nothing happens. I'll try with a different browser just in case ...

**Comment by lesteve** [comment]
Same thing with a different browser ...

**Comment by lesteve** [comment]
OK I think the crucial part is that I don't get the blue button "Renouveler le dossier" in the screenshot from your doc:
![image](https://user-images.githubusercontent.com/1680079/101605199-30eb3a80-3a02-11eb-9332-7fe4fc8c949f.png)

By the way you have an AD number in your doc :scream: I thought this was super-confidential information that nobody is supposed to leak because to avoid social engineering attacks

**Comment by RemiLacroix-IDRIS** [comment]
> OK I think the crucial part is that I don't get the blue button "Renouveler le dossier" in the screenshot from your doc:

Ok, that's what we wanted to be sure of.

> By the way you have an AD number in your doc scream I thought this was super-confidential information that nobody is supposed to leak to avoid social engineering attacks

Ok, you got us there... Can you remove the image from your message? We will correct them on our documentation.

**Comment by lesteve** [comment]
I was half-joking since I imagine that the project in question was only a test project. I blurred the problematic info in the screenshot.

**Comment by lesteve** [comment]
I did not even know this, but it turns out you can delete old revisions from comments (which I did): https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/tracking-changes-in-a-comment#deleting-sensitive-information-from-a-comments-history, I learned something this is nice.

**Comment by lesteve** [comment]
OK it looks like my status was not filled in https://www.edari.fr/utilisateur/profil, updating my status seems to make the button appear again.
