### ISSUE TITLE
Document using tensorboard.dev as an alternative than sshfs + locally running tensorboard

### ISSUE THREAD

**Issue by lesteve** [jean-zay-users/jean-zay-doc#56]
From @zaccharieramzi on the gitter chat: https://gitter.im/jean-zay-users/jean-zay-doc?at=6007f8e5d8bdab473949919a

Re tensorboard, an option that I am using, which of course is not ideal, is to launch tensorboard dev (https://tensorboard.dev/) in a screen on one of the frontal nodes.
This allows me to monitor my trainings online without having to log in to JZ.
For example this is a dead session: https://tensorboard.dev/experiment/NIMi5kviRuOktlOwKxQIxw/#scalars

The problem is of course that it is killed at some point but it lasts for about 11 hours so it's decent. Ideally it could be just a process that lives on forever.

**Comment by zaccharieramzi** [comment]
This was handled in https://github.com/jean-zay-users/jean-zay-doc/pull/57, I am therefore closing this.
We should have another issue to document the [`sshfs` solution](https://github.com/jean-zay-users/jean-zay-doc/pull/57#issuecomment-764204533).
