### ISSUE TITLE
using Kaldi

### ISSUE THREAD

**Issue by kermorvant** [jean-zay-users/jean-zay-doc#61]
There is a kaldi module : 

```
module avail kaldi
/gpfslocalsup/pub/modules-idris-env4/modulefiles/linux-rhel8-skylake_avx512 
kaldi/master-cuda
```
but SRIM/openfst seem not to be installed.

Anyone has been using kaldi on JeanZay ?

**Comment by lesteve** [comment]
Never heard of kaldi myself but maybe try asking in the [gitter chat](https://gitter.im/jean-zay-users/jean-zay-doc) and see what happens?

**Comment by lesteve** [comment]
Actually I had a vague recollection that it was linked to NLP so I am guessing this is https://github.com/kaldi-asr/kaldi.

It seems like `kaldi` is available in `conda-forge` `conda install -c conda-forge kaldi`, maybe worth a try ...

**Comment by RemiLacroix-IDRIS** [comment]
Kaldi and OpenFST are already installed on Jean Zay and are available using `module load`.

SRILM will be made available soon (tomorrow hopefully).

**Comment by kermorvant** [comment]
Thanks very much Remi, I am impressed by the support on IDIRS 👍

**Comment by lesteve** [comment]
Closing this one, thanks @RemiLacroix-IDRIS for your input.
