### ISSUE TITLE
Caveat with unzipped or untarred archive on SCRATCH

### ISSUE THREAD

**Issue by lesteve** [jean-zay-users/jean-zay-doc#62]
https://gitter.im/jean-zay-users/jean-zay-doc?at=5e8b1b1716f84f04615d0058

It seems like by default `unzip` or `tar` keep the modification and access time of the original files when the archive was created. This cause the files on SCRATCH to be wiped out although you unzipped the archive recently.

People are getting caught by this from time to time, this should be mentioned as a caveat with SCRATCH (with potentially an example of unzipping a common dataset from DSDIR (e.g. coco as in https://gitter.im/jean-zay-users/jean-zay-doc?at=606737053153ce63a3b5a1c5)

The work-around is to use `tar -m` or `unzip -DD` so that the extracted files have the timestamp of archive extraction.

**Comment by rstrudel** [comment]
Cf #63 for an update in the doc
