### ISSUE TITLE
Broken link in Project description

### ISSUE THREAD

**Issue by zaccharieramzi** [jean-zay-users/jean-zay-doc#66]
The following link, https://www.edari.fr/voirlappel56, is broken. I don't know what it was refering to.

The section where the link appears is the [Project Description](https://jean-zay-doc.readthedocs.io/en/latest/access-procedure/#declaration-de-dossier-project-description).

**Comment by lesteve** [comment]
I removed it in https://github.com/jean-zay-users/jean-zay-doc/commit/83ddf8f69c3c9e3df558282e9dd32e786e78ef28. Basically IIRC the link was saying exactly what was in the text i.e. "ask for less than 10k hours and they shall be granted" or maybe some general context about dynamic access for IA.
