### ISSUE TITLE
Creating a conda environment

### ISSUE THREAD

**Issue by keenjo** [jean-zay-users/jean-zay-doc#93]
Has anyone ever successfully created their own conda environment on jean zay? I find that any time I attempt to do so I run out of memory in my $WORK directory, even when the directory starts empty. Note that I am using the jean zay anaconda module, so there is no issue with my own installation of anaconda or miniconda taking up space. I've also tried using the given PyTorch module as my environment, but it does not work with my scripts.

**Comment by RemiLacroix-IDRIS** [comment]
Hi. Yes, using personal Conda environment is possible on Jean Zay. Did you follow the steps described on [our documentation](http://www.idris.fr/eng/jean-zay/gpu/jean-zay-gpu-python-env-eng.html) regarding moving `~/.conda` to `$WORK/.conda` using a symbolic link?

**Comment by keenjo** [comment]
I believe I have already tried that but I'll give it another go to see if it works!

**Comment by RemiLacroix-IDRIS** [comment]
The problem had been solved. It was a problem with the symbolic link. Additionally it turns out our PyTorch modules works fine with the keenjo's code.
